server:
  port: ${PORT:8080}

spring:
  application:
    name: energiAI-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # Define 'local' se nada for informado

management:
  endpoints:
    web:
      exposure:
        include: health,info # Expõe apenas dados seguros do Actuator
